# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20171120_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_appreciation',
            field=models.IntegerField(default=0),
        ),
    ]
