# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20171122_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='liked_questions',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='voted_questions',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
