# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_detail',
            field=models.CharField(default='why why why', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='questioner_name',
            field=models.CharField(default='jiangzhihao', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=50),
        ),
    ]
